// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UFVSzWjhsyBIj8N8ecde-ixnq6dgXUs',
    appId: '1:350383415335:web:YOUR_WEB_APP_ID', // Add web app to get this
    messagingSenderId: '350383415335',
    projectId: 'eduportal-b3ca3',
    authDomain: 'eduportal-b3ca3.firebaseapp.com',
    storageBucket: 'eduportal-b3ca3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5UFVSzWjhsyBIj8N8ecde-ixnq6dgXUs', // Same as web API key
    appId: '1:350383415335:android:25f5a371c100b2400fae02',
    messagingSenderId: '350383415335',
    projectId: 'eduportal-b3ca3', // Get from Firebase Console → Project Settings → General
    storageBucket: 'eduportal-b3ca3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5UFVSzWjhsyBIj8N8ecde-ixnq6dgXUs',
    appId: '1:350383415335:ios:YOUR_IOS_APP_ID', // Add iOS app to get this
    messagingSenderId: '350383415335',
    projectId: 'eduportal-b3ca3',
    storageBucket: 'eduportal-b3ca3.appspot.com',
    iosBundleId: 'com.example.testtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5UFVSzWjhsyBIj8N8ecde-ixnq6dgXUs',
    appId: '1:350383415335:ios:YOUR_MACOS_APP_ID', // Add macOS app to get this
    messagingSenderId: '350383415335',
    projectId: 'eduportal-b3ca3',
    storageBucket: 'eduportal-b3ca3.appspot.com',
    iosBundleId: 'com.example.testtt',
  );
}
